### ISSUE TITLE
Any chance you are the hazzaaclark which released previously chuchu?

### ISSUE THREAD

**Issue by futurepr0n** [hazzaclark/gdiGhidra#3]
There was an IDA plugin for dreamcast, but its gone missing on github. Any chance if that was you could you reshare it?

**Comment by hazzaclark** [comment]
Hi - thank you for your message
While that was me, I have long since deleted that repository due to not feeling as though it was needed 

Not to mention, the code barely worked and or functioned

Should there ever come a point whereby I want to continue those developments, you can always keep tabs on my profile for any updates pertaining towards that

God Bless

**Comment by futurepr0n** [comment]
Appreciate your reply and will follow along with your public progress on these projects you have! thanks for pursuing this stuff!
